language: node_js
node_js:
  - "6"
dist: trusty

before_install:
  - nvm install $(cat .nvmrc)
  - node -v

  # Yarn install instructions from https://yarnpkg.com/en/docs/install#linux-tab
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - ./ci-bin/retry.bash sudo apt-get update
  - sudo apt-get install yarn=1.2.1-1

  # Travis has an old version of yarn installed at /usr/local/bin, and that comes first in the PATH,
  # so we need to explicitly point to the version of Yarn we just installed.
  - export YARN=/usr/bin/yarn
  
  - $YARN --version
  - $YARN --frozen-lockfile

  # TODO Maybe we don't need to still do this hack?
  - wget https://s3-us-gov-west-1.amazonaws.com/dsva-appeals-devops/chromium-chromedriver_53.0.2785.143-0ubuntu0.14.04.1.1145_amd64.deb -O $PWD/chromium-chromedriver.deb
  - sudo dpkg -i $PWD/chromium-chromedriver.deb
  - sudo apt-get install -f
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"

cache:
  yarn: true

notifications:
  email: false
