language: node_js
node_js:
  - "6"
dist: trusty

before_install:
  - nvm install $(cat .nvmrc)
  - node -v

  # Yarn install instructions from https://yarnpkg.com/en/docs/install#linux-tab
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - ./ci-bin/retry.bash sudo apt-get update
  - sudo apt-get install yarn=1.2.1-1

  # Travis has an old version of yarn installed at /usr/local/bin, and that comes first in the PATH,
  # so we need to explicitly point to the version of Yarn we just installed.
  - export YARN=/usr/bin/yarn
  
  - $YARN --version
  - $YARN --frozen-lockfile

cache:
  yarn: true

notifications:
  email: false
